[package]
name = "mailin"
version = "0.6.5"
authors = ["alienscience <saul@alienscience.org.uk>"]
exclude = ["docs/*"]
description = "A library for writing SMTP servers"
repository = 'https://code.alienscience.org/alienscience/mailin'
readme = "README.md"
keywords = ["smtp","server","email"]
categories = ["email","network-programming"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
nom = "7"
log = "0.4"
base64-compat = "1"
ternop = "1.0"
either = "1.5"
tokio = { version = "1.40.0", features = ["io-util"] }
